### ISSUE TITLE
README.md में गलतियां

### ISSUE THREAD

**Issue by jatin-code777** [vijayphoenix/Car-racing-game#6]
हमें आपकी रीडमी में कुछ गलतियां मिली हैं |
कृपया करके उन्हें सुधार लीजिये |
कुछ उद्धरण यहाँ पर पेश किये जा रहे हैं :
१. equiped की वर्तनी equipped होनी चाहिए 
२. cops cars को cop cars से बदला जाना चाहिए 
...इत्यादि 

आपका शुभचिंतक 
जतिन शर्मा

**Comment by vijayphoenix** [comment]
आपके बदलावों को शामिल कर लिया गया है
